trigger:
- main
- release/*
- beta/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install' 
    verbose: false

- task: Npm@1
  displayName: 'npm run rollup'
  inputs:
    command: custom 
    verbose: false
    customCommand: 'run rollup'

- task: Npm@1
  displayName: 'npm publish beta (conditionally)'
  inputs:
    command: custom
    verbose: false
    customCommand: 'publish --tag beta'
    publishEndpoint: npm
    customEndpoint: npm
  continueOnError: true
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/beta'))
