trigger:
- main
- release/*
- beta/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install' 
    verbose: false

- task: Npm@1
  displayName: 'npm run rollup'
  inputs:
    command: custom 
    verbose: false
    customCommand: 'run rollup'


- task: Npm@1
  displayName: 'npm publish beta (conditionally)'
  inputs:
    command: custom
    verbose: false
    customCommand: 'publish --tag beta'
    publishEndpoint: npm
    customEndpoint: npm
    publishRegistry: 'useFeed'
    publishFeed: '491d3f0d-0acb-4801-8cdb-7abfdb2786ae'
  continueOnError: true
